### ISSUE TITLE
Dropdown component used across the UI is missing localized string for case when no options are available

### ISSUE THREAD

**Issue by esuomi** [entur/enki#1379]
In various places, such as when creating a new line or selecting an authority to a new network, if there's no options available at all, the dropdown component shows

> _Ingen treff for søket_

as the default text;
![Screenshot 2024-05-23 at 15 23 09](https://github.com/entur/enki/assets/1393900/fa74ad70-bab2-4fe8-88b5-6f484c815385)

This string is not localized. From what I can gather, it seems to come from within the component itself (`@entur/dropdown`?) and since it repeats everywhere where the dropdown component is used, the problem should be isolated in the component itself.

**Comment by testower** [comment]
Thanks for reporting! I actually noticed this while working on a fix for #1377. There should definitely be a more sensible and localized placeholder value here.

**Comment by testower** [comment]
So this seems to be an issue with the component itself. I'll report it.

**Comment by testower** [comment]
I think this has been resolved now, if not you can reopen.

**Comment by testower** [comment]
Still not fixed upstream it seems

**Comment by testower** [comment]
Internal reference: [ETU-48858](https://enturas.atlassian.net/browse/ETU-48858)
